"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, BellRing, Bot, Check, CheckCircle2, ChevronRight, CreditCard, Gift, Globe2, Headphones, Instagram, Landmark, MessageCircle, Play, RefreshCw, Send, ShieldCheck, ShoppingBag, Sparkles, Store, TicketCheck, TrendingUp, Users, Wallet } from "lucide-react";

const steps = [
  { title: "Set up shop", label: "START", icon: Store },
  { title: "Sell everywhere", label: "DISCOVER", icon: ShoppingBag },
  { title: "Serve customers", label: "SUPPORT", icon: Headphones },
  { title: "Track dues", label: "OPERATE", icon: Wallet },
  { title: "Spot growth", label: "UNDERSTAND", icon: BarChart3 },
  { title: "Bring people back", label: "GROW", icon: Gift },
  { title: "Find support", label: "EXPAND", icon: Landmark },
  { title: "See the impact", label: "RESULT", icon: TrendingUp },
];

const content = [
  { eyebrow: "A MERCHANT'S NEW BEGINNING", title: "Meera takes her shop online.", body: "She adds a few products and connects her business records. SAHAKAR creates a digital home for her store, while Saha gets the context it needs to help.", saha: "Your store is ready. I can help you manage orders, customers, inventory, payments, and khata from here." },
  { eyebrow: "ONE ORDER, ANY CHANNEL", title: "A customer finds her where they already are.", body: "A shopper discovers a product through WhatsApp or Instagram, places an order, and pays through a Paytm powered checkout. The order and payment appear together.", saha: "New order received! I've added it to your orders and updated the payment record." },
  { eyebrow: "HELP THAT DOESN'T KEEP PEOPLE WAITING", title: "A customer needs help. Saha is there.", body: "Saha handles common questions using store policies. When an issue needs a person, it verifies details, creates a ticket, and escalates it for review.", saha: "I found the order and asked for a photo. The issue is verified and ready for Meera to review." },
  { eyebrow: "NO MORE LOST FOLLOW UPS", title: "The khata remembers what is due.", body: "Credit and outstanding balances live beside transactions. Saha spots an upcoming due and prepares a friendly reminder by message or voice.", saha: "Ravi's ₹2,400 payment is due soon. I've drafted a polite WhatsApp reminder." },
  { eyebrow: "FROM DATA TO DECISIONS", title: "A pattern becomes an opportunity.", body: "The connected sales and customer picture reveals repeat purchase trends, quiet customers, and what may be worth doing next.", saha: "18 regular customers haven't visited in 30 days. A tailored offer could help bring them back." },
  { eyebrow: "RIGHT OFFER, RIGHT CUSTOMER", title: "Meera makes it personal.", body: "Saha groups the right customers and drafts an offer. Loyalty and discount rules can make repeat visits more rewarding.", saha: "I've prepared a comeback offer for customers who have gone quiet. You can review it before sending." },
  { eyebrow: "MORE WAYS TO MOVE FORWARD", title: "Growth support goes beyond sales.", body: "Saha surfaces relevant government schemes and explains why a merchant may qualify and what to prepare for an application.", saha: "I found a potential MSME scheme match. Let's check eligibility and the documents needed." },
  { eyebrow: "ONE CONNECTED BUSINESS", title: "A calmer day. A stronger tomorrow.", body: "The same business brain links storefront, conversations, orders, payments, khata, and growth actions. Meera keeps the final say while Saha helps with the work.", saha: "All caught up. Your orders, support cases, dues, and next growth actions are in one place." },
];

type Channel = "WhatsApp" | "Instagram" | "Web store";

export default function Demo() {
  const [step, setStep] = useState(0);
  const [channel, setChannel] = useState<Channel>("WhatsApp");
  const [ticket, setTicket] = useState(false);
  const [reminder, setReminder] = useState(false);
  const [offer, setOffer] = useState(false);
  const [scheme, setScheme] = useState(false);
  const [message, setMessage] = useState("");
  const [reply, setReply] = useState("");
  const current = content[step];
  const reset = () => { setStep(0); setChannel("WhatsApp"); setTicket(false); setReminder(false); setOffer(false); setScheme(false); setMessage(""); setReply(""); };
  const askSaha = () => {
    if (!message.trim()) return;
    const q = message.toLowerCase();
    setReply(q.includes("sale") ? "Meera's sample store has ₹12,480 in sales today across 32 orders." : q.includes("product") ? "In a full product, I could add the product for you. This concept demo shows the merchant flow without saving data." : "I can help with store updates, orders, payments, customer questions, dues, and growth ideas. This is a scripted concept demo.");
    setMessage("");
  };
  return <section className="demo-section" id="demo"><div className="container"><div className="demo-heading"><div><span className="eyebrow"><span className="eyebrow-line" /> INTERACTIVE CONCEPT DEMO</span><h2>Step into Meera&apos;s day.</h2><p>Click through the complete merchant journey. Every screen uses sample data to show how the product would feel.</p></div><span className="demo-hint"><Play size={15} fill="currentColor" /> 3 MINUTE WALKTHROUGH</span></div>
    <div className="demo-shell"><div className="demo-progress"><div className="demo-progress-top"><span>THE SAHAKAR EXPERIENCE</span><span>{String(step + 1).padStart(2, "0")} / {String(steps.length).padStart(2, "0")}</span></div><div className="progress-track"><span style={{width:`${((step + 1) / steps.length) * 100}%`}} /></div><div className="step-tabs" role="tablist" aria-label="Demo steps">{steps.map((s, i) => <button key={s.title} role="tab" aria-selected={step === i} className={`${step === i ? "active" : ""} ${i < step ? "visited" : ""}`} onClick={() => setStep(i)}><span>{i < step ? <Check size={14} /> : <s.icon size={15} />}</span><small>{s.title}</small></button>)}</div></div>
      <div className="demo-content"><div className="demo-narrative"><span className="demo-step-label">CHAPTER {String(step + 1).padStart(2, "0")} <span /> {current.eyebrow}</span><h3>{current.title}</h3><p>{current.body}</p><div className="saha-says"><span className="saha-face"><Bot size={25} /></span><div><small>SAHA SAYS</small><p>“{current.saha}”</p></div></div><div className="demo-controls"><button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}><ArrowLeft size={17} /> Back</button>{step === steps.length - 1 ? <button className="next-control" onClick={reset}><RefreshCw size={17} /> Replay demo</button> : <button className="next-control" onClick={() => setStep(step + 1)}>Next chapter <ArrowRight size={17} /></button>}</div></div>
        <div className="demo-stage"><div className="stage-top"><span><span className="stage-live" /> SAHAKAR LIVE PREVIEW</span><span>MEERA&apos;S STORE <ChevronRight size={14} /></span></div><div className="stage-body" key={step}>
          {step === 0 && <div className="stage-store"><div className="stage-welcome"><span className="stage-logo">M</span><div><small>MERCHANT WORKSPACE</small><h4>Meera&apos;s Store</h4></div><span className="stage-status"><Check size={13} /> Store live</span></div><div className="stage-hero"><div><small>YOUR DIGITAL STOREFRONT</small><h5>Your neighborhood favorites, now online.</h5><span>Browse, order, and pay from anywhere.</span></div><Store size={54} strokeWidth={1.2} /></div><div className="stage-products"><div><span>☕</span><b>Masala Chai</b><small>₹80 · 24 in stock</small></div><div><span>🍯</span><b>Wild Honey</b><small>₹320 · 12 in stock</small></div><div><span>🫙</span><b>Homemade Pickle</b><small>₹180 · 18 in stock</small></div></div><div className="stage-check"><CheckCircle2 size={17} /> Products, inventory, and business records connected</div></div>}
          {step === 1 && <div className="stage-order"><div className="stage-caption">CHOOSE A DISCOVERY CHANNEL</div><div className="channel-buttons">{([{name:"WhatsApp",icon:MessageCircle},{name:"Instagram",icon:Instagram},{name:"Web store",icon:Globe2}] as const).map(c => <button key={c.name} className={channel === c.name ? "selected" : ""} onClick={() => setChannel(c.name)}><c.icon size={18} />{c.name}</button>)}</div><div className="order-preview"><div><span className="order-icon"><ShoppingBag size={22} /></span><div><small>NEW ORDER VIA {channel.toUpperCase()}</small><b>Order #SK-2048</b></div><span className="order-new">NEW</span></div><div className="order-item"><span>🍯</span><span>Wild Honey × 1<br /><small>Homemade Pickle × 1</small></span><b>₹500</b></div><div className="order-total"><span>Total</span><strong>₹500</strong></div><div className="payment-success"><CreditCard size={18} /><span>Paid securely with Paytm</span><CheckCircle2 size={18} /></div></div></div>}
          {step === 2 && <div className="stage-support"><div className="chat-window"><div className="chat-window-head"><span className="chat-avatar">A</span><span><b>Aarav · Customer</b><small>WhatsApp support</small></span><span className="active-tag">ACTIVE</span></div><div className="chat-msg customer-msg">Hi, my honey jar arrived damaged. Can you help?</div><div className="chat-msg saha-msg"><span><Sparkles size={12} /> SAHA</span> I&apos;m sorry. Please share a photo and your order ID so I can verify the issue.</div><div className="chat-msg customer-msg">Order #SK-2048. I&apos;ve sent a photo.</div><div className="chat-msg saha-msg"><span><Sparkles size={12} /> SAHA</span> Thank you. I&apos;ve verified your order and will create a ticket for Meera to review.</div></div><button className={`stage-action ${ticket ? "done" : ""}`} onClick={() => setTicket(!ticket)}>{ticket ? <><CheckCircle2 size={17} /> Ticket #1024 verified and escalated</> : <><ShieldCheck size={17} /> Verify issue & create ticket <ArrowRight size={17} /></>}</button></div>}
          {step === 3 && <div className="stage-dues"><div className="due-summary"><span><small>TOTAL PENDING</small><strong>₹7,800</strong></span><span><Wallet size={23} /></span></div><div className="due-row"><span className="customer-avatar">RK</span><span><b>Ravi Kumar</b><small>Due in 2 days · Grocery credit</small></span><strong>₹2,400</strong></div><div className="due-row"><span className="customer-avatar alt">SP</span><span><b>Sana Patel</b><small>1 day overdue · Bulk order</small></span><strong>₹1,200</strong></div><div className="reminder-card"><BellRing size={19} /><span><b>Friendly reminder for Ravi</b><small>“Hi Ravi, a quick reminder that ₹2,400 is due in 2 days. Thank you!”</small></span></div><button className={`stage-action ${reminder ? "done" : ""}`} onClick={() => setReminder(!reminder)}>{reminder ? <><CheckCircle2 size={17} /> Sample reminder marked sent</> : <><Send size={17} /> Send sample reminder <ArrowRight size={17} /></>}</button></div>}
          {step === 4 && <div className="stage-insights"><div className="insight-metrics"><div><small>THIS WEEK&apos;S SALES</small><b>₹48,250</b><span>↗ 12% vs last week</span></div><div><small>REPEAT CUSTOMERS</small><b>42</b><span>↗ 8 new regulars</span></div></div><div className="chart-card"><div><b>Weekly sales</b><small>MON — SUN</small></div><div className="chart-bars">{[35,53,43,70,55,89,76].map((height,i) => <span key={i} style={{height:`${height}%`}} />)}</div><div className="chart-days">{["M","T","W","T","F","S","S"].map((d,i)=><span key={i}>{d}</span>)}</div></div><div className="insight-callout"><Sparkles size={21} /><span><b>A chance to reconnect</b><small>18 regulars have not bought in 30 days. Try a personal offer.</small></span></div></div>}
          {step === 5 && <div className="stage-offer"><div className="offer-target"><Users size={21} /><span><small>AUDIENCE SUGGESTED BY SAHA</small><b>18 customers to reconnect with</b></span><CheckCircle2 size={18} /></div><div className="offer-card"><span className="offer-tag">A LITTLE SOMETHING FOR YOU</span><span className="offer-emoji">🎁</span><h5>Come back & save 10%</h5><p>A thoughtful offer for customers who haven&apos;t visited in a while.</p><div><span>Audience · 18 customers</span><span>Discount · 10%</span></div></div><button className={`stage-action ${offer ? "done" : ""}`} onClick={() => setOffer(!offer)}>{offer ? <><CheckCircle2 size={17} /> Sample campaign ready for review</> : <><Gift size={17} /> Prepare sample offer <ArrowRight size={17} /></>}</button></div>}
          {step === 6 && <div className="stage-scheme"><div className="scheme-header"><Landmark size={25} /><span><small>GOVERNMENT SCHEME FINDER</small><b>Potential match for Meera</b></span></div><div className="scheme-card"><span className="match-badge"><Sparkles size={13} /> POSSIBLE MATCH</span><h5>MSME business support</h5><p>Explore programs that may support small business growth and digitization.</p><div><Check size={15} /> Check business eligibility</div><div><Check size={15} /> Review required documents</div><div><Check size={15} /> See application guidance</div></div><button className={`stage-action ${scheme ? "done" : ""}`} onClick={() => setScheme(!scheme)}>{scheme ? <><CheckCircle2 size={17} /> Sample checklist opened</> : <><Landmark size={17} /> View sample checklist <ArrowRight size={17} /></>}</button>{scheme && <div className="scheme-note">Have registration details, business category, and relevant financial records ready. Actual eligibility depends on the current scheme rules.</div>}</div>}
          {step === 7 && <div className="stage-finish"><div className="finish-logo"><Bot size={38} /></div><h4>One clearer view of Meera&apos;s business.</h4><p>Saha connects the work happening across her day.</p><div className="finish-grid">{[{icon:ShoppingBag,label:"Orders",value:"32 today"},{icon:CreditCard,label:"Payments",value:"₹12,480"},{icon:TicketCheck,label:"Support",value:"1 to review"},{icon:Wallet,label:"Khata",value:"3 dues"},{icon:Gift,label:"Growth",value:"1 offer ready"},{icon:Landmark,label:"Schemes",value:"1 match"}].map(item=><div key={item.label}><item.icon size={19} /><span><small>{item.label}</small><b>{item.value}</b></span></div>)}</div><div className="finish-outcome"><CheckCircle2 size={19} /> More digital sales · Less manual work · Better decisions</div></div>}
        </div><div className="stage-bottom"><span><Sparkles size={14} /> Frontend concept demo · sample data only</span><span>Powered by the idea of Saha</span></div></div>
      </div>
    </div>
    <div className="demo-agent"><span className="agent-circle"><Bot size={24} /></span><div><b>Ask Saha, in everyday language.</b><p>Try “Show today&apos;s sales” or “Add a product”.</p></div><div className="agent-input"><input aria-label="Ask Saha a sample question" value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")askSaha();}} placeholder="Ask Saha something..." /><button aria-label="Send question" onClick={askSaha}><ArrowRight size={18} /></button></div>{reply && <div className="agent-reply"><Sparkles size={15} />{reply}</div>}</div>
  </div></section>;
}
